"""updating models

Revision ID: 5b53f6e5ff2d
Revises: 5cdcaf15459b
Create Date: 2025-12-19 18:27:12.234226

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5b53f6e5ff2d'
down_revision = '5cdcaf15459b'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('customer_profiles', 'company_name',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_index('ix_customer_profiles_user_id', table_name='customer_profiles')
    op.create_index(op.f('ix_customer_profiles_company_name'), 'customer_profiles', ['company_name'], unique=True)
    op.drop_constraint('customer_profiles_user_id_fkey', 'customer_profiles', type_='foreignkey')
    op.drop_column('customer_profiles', 'user_id')
    op.add_column('printing_jobs', sa.Column('customer_profile_id', sa.Integer(), nullable=False))
    op.drop_index('ix_printing_jobs_customer_id', table_name='printing_jobs')
    op.create_index(op.f('ix_printing_jobs_customer_profile_id'), 'printing_jobs', ['customer_profile_id'], unique=False)
    op.drop_constraint('printing_jobs_customer_id_fkey', 'printing_jobs', type_='foreignkey')
    op.create_foreign_key(None, 'printing_jobs', 'customer_profiles', ['customer_profile_id'], ['id'], ondelete='CASCADE')
    op.drop_column('printing_jobs', 'customer_id')
    op.add_column('users', sa.Column('customer_profile_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_users_customer_profile_id'), 'users', ['customer_profile_id'], unique=False)
    op.create_foreign_key(None, 'users', 'customer_profiles', ['customer_profile_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.drop_index(op.f('ix_users_customer_profile_id'), table_name='users')
    op.drop_column('users', 'customer_profile_id')
    op.add_column('printing_jobs', sa.Column('customer_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'printing_jobs', type_='foreignkey')
    op.create_foreign_key('printing_jobs_customer_id_fkey', 'printing_jobs', 'users', ['customer_id'], ['id'], ondelete='CASCADE')
    op.drop_index(op.f('ix_printing_jobs_customer_profile_id'), table_name='printing_jobs')
    op.create_index('ix_printing_jobs_customer_id', 'printing_jobs', ['customer_id'], unique=False)
    op.drop_column('printing_jobs', 'customer_profile_id')
    op.add_column('customer_profiles', sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.create_foreign_key('customer_profiles_user_id_fkey', 'customer_profiles', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_index(op.f('ix_customer_profiles_company_name'), table_name='customer_profiles')
    op.create_index('ix_customer_profiles_user_id', 'customer_profiles', ['user_id'], unique=False)
    op.alter_column('customer_profiles', 'company_name',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###

