"""initial_migaration

Revision ID: 5cdcaf15459b
Revises: 
Create Date: 2025-12-19 15:30:05.954954

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5cdcaf15459b'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('uuid', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('role', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_uuid'), 'users', ['uuid'], unique=True)
    op.create_table('customer_profiles',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('uuid', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('company_name', sa.String(), nullable=True),
    sa.Column('contact_name', sa.String(), nullable=True),
    sa.Column('phone', sa.String(), nullable=True),
    sa.Column('address', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_customer_profiles_user_id'), 'customer_profiles', ['user_id'], unique=True)
    op.create_index(op.f('ix_customer_profiles_uuid'), 'customer_profiles', ['uuid'], unique=True)
    op.create_table('printer_profiles',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('uuid', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('business_name', sa.String(), nullable=False),
    sa.Column('contact_name', sa.String(), nullable=True),
    sa.Column('phone', sa.String(), nullable=True),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('address', sa.Text(), nullable=True),
    sa.Column('capabilities', sa.Text(), nullable=True),
    sa.Column('supported_product_types', sa.Text(), nullable=False),
    sa.Column('min_quantity', sa.Integer(), nullable=True),
    sa.Column('max_quantity', sa.Integer(), nullable=True),
    sa.Column('service_areas', sa.Text(), nullable=True),
    sa.Column('payment_terms', sa.Text(), nullable=False),
    sa.Column('email_notifications', sa.Boolean(), nullable=False),
    sa.Column('whatsapp_notifications', sa.Boolean(), nullable=False),
    sa.Column('whatsapp_number', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_printer_profiles_user_id'), 'printer_profiles', ['user_id'], unique=True)
    op.create_index(op.f('ix_printer_profiles_uuid'), 'printer_profiles', ['uuid'], unique=True)
    op.create_table('printing_jobs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('uuid', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('customer_id', sa.Integer(), nullable=False),
    sa.Column('product_type', sa.String(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('due_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('special_instructions', sa.Text(), nullable=True),
    sa.Column('file_url', sa.String(), nullable=True),
    sa.Column('bidding_duration_hours', sa.Integer(), nullable=False),
    sa.Column('bidding_ends_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('delivery_location', sa.Text(), nullable=True),
    sa.Column('pickup_preferred', sa.Boolean(), nullable=False),
    sa.Column('state', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('closed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint('bidding_duration_hours > 0', name='bidding_duration_positive'),
    sa.CheckConstraint('quantity > 0', name='quantity_positive'),
    sa.ForeignKeyConstraint(['customer_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_printing_jobs_customer_id'), 'printing_jobs', ['customer_id'], unique=False)
    op.create_index(op.f('ix_printing_jobs_state'), 'printing_jobs', ['state'], unique=False)
    op.create_index(op.f('ix_printing_jobs_uuid'), 'printing_jobs', ['uuid'], unique=True)
    op.create_table('bids',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('uuid', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('job_id', sa.Integer(), nullable=False),
    sa.Column('printer_id', sa.Integer(), nullable=False),
    sa.Column('price', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('estimated_turnaround_days', sa.Integer(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('payment_terms', sa.Text(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('accepted_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint('estimated_turnaround_days >= 0', name='turnaround_non_negative'),
    sa.CheckConstraint('price > 0', name='price_positive'),
    sa.ForeignKeyConstraint(['job_id'], ['printing_jobs.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['printer_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('job_id', 'printer_id', name='uq_bid_job_printer')
    )
    op.create_index(op.f('ix_bids_job_id'), 'bids', ['job_id'], unique=False)
    op.create_index(op.f('ix_bids_printer_id'), 'bids', ['printer_id'], unique=False)
    op.create_index(op.f('ix_bids_status'), 'bids', ['status'], unique=False)
    op.create_index(op.f('ix_bids_uuid'), 'bids', ['uuid'], unique=True)
    op.create_table('ratings',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('uuid', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('job_id', sa.Integer(), nullable=False),
    sa.Column('printer_profile_id', sa.Integer(), nullable=False),
    sa.Column('customer_id', sa.Integer(), nullable=False),
    sa.Column('rating', sa.Integer(), nullable=False),
    sa.Column('feedback', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint('rating >= 1 AND rating <= 5', name='rating_range'),
    sa.ForeignKeyConstraint(['customer_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['job_id'], ['printing_jobs.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['printer_profile_id'], ['printer_profiles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ratings_customer_id'), 'ratings', ['customer_id'], unique=False)
    op.create_index(op.f('ix_ratings_job_id'), 'ratings', ['job_id'], unique=True)
    op.create_index(op.f('ix_ratings_printer_profile_id'), 'ratings', ['printer_profile_id'], unique=False)
    op.create_index(op.f('ix_ratings_uuid'), 'ratings', ['uuid'], unique=True)
    op.create_table('agreements',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('uuid', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('job_id', sa.Integer(), nullable=False),
    sa.Column('bid_id', sa.Integer(), nullable=False),
    sa.Column('customer_id', sa.Integer(), nullable=False),
    sa.Column('printer_id', sa.Integer(), nullable=False),
    sa.Column('agreed_price', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('agreed_turnaround_days', sa.Integer(), nullable=False),
    sa.Column('payment_terms', sa.Text(), nullable=False),
    sa.Column('customer_confirmed', sa.Boolean(), nullable=False),
    sa.Column('confirmation_timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['bid_id'], ['bids.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['customer_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['job_id'], ['printing_jobs.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['printer_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_agreements_bid_id'), 'agreements', ['bid_id'], unique=True)
    op.create_index(op.f('ix_agreements_customer_id'), 'agreements', ['customer_id'], unique=False)
    op.create_index(op.f('ix_agreements_job_id'), 'agreements', ['job_id'], unique=True)
    op.create_index(op.f('ix_agreements_printer_id'), 'agreements', ['printer_id'], unique=False)
    op.create_index(op.f('ix_agreements_uuid'), 'agreements', ['uuid'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_agreements_uuid'), table_name='agreements')
    op.drop_index(op.f('ix_agreements_printer_id'), table_name='agreements')
    op.drop_index(op.f('ix_agreements_job_id'), table_name='agreements')
    op.drop_index(op.f('ix_agreements_customer_id'), table_name='agreements')
    op.drop_index(op.f('ix_agreements_bid_id'), table_name='agreements')
    op.drop_table('agreements')
    op.drop_index(op.f('ix_ratings_uuid'), table_name='ratings')
    op.drop_index(op.f('ix_ratings_printer_profile_id'), table_name='ratings')
    op.drop_index(op.f('ix_ratings_job_id'), table_name='ratings')
    op.drop_index(op.f('ix_ratings_customer_id'), table_name='ratings')
    op.drop_table('ratings')
    op.drop_index(op.f('ix_bids_uuid'), table_name='bids')
    op.drop_index(op.f('ix_bids_status'), table_name='bids')
    op.drop_index(op.f('ix_bids_printer_id'), table_name='bids')
    op.drop_index(op.f('ix_bids_job_id'), table_name='bids')
    op.drop_table('bids')
    op.drop_index(op.f('ix_printing_jobs_uuid'), table_name='printing_jobs')
    op.drop_index(op.f('ix_printing_jobs_state'), table_name='printing_jobs')
    op.drop_index(op.f('ix_printing_jobs_customer_id'), table_name='printing_jobs')
    op.drop_table('printing_jobs')
    op.drop_index(op.f('ix_printer_profiles_uuid'), table_name='printer_profiles')
    op.drop_index(op.f('ix_printer_profiles_user_id'), table_name='printer_profiles')
    op.drop_table('printer_profiles')
    op.drop_index(op.f('ix_customer_profiles_uuid'), table_name='customer_profiles')
    op.drop_index(op.f('ix_customer_profiles_user_id'), table_name='customer_profiles')
    op.drop_table('customer_profiles')
    op.drop_index(op.f('ix_users_uuid'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###

